name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc upx-ucl

      - name: Build all
        run: |
          sed -i 's/$$PWD\/tools\/upx-3.91-amd64_linux\/upx/upx-ucl/g' game_box.pro
          qmake -makefile
          make
      
      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: game_box
          path: |
            ./release/out/game_box
      
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      
      - name: MSVC Environment Setup
        uses: ilammy/msvc-dev-cmd@v1
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          arch: win64_mingw81
          
      - name: Build all
        run: |
          qmake -makefile
          mingw32-make
          windeployqt.exe ./release/out/game_box.exe
          
      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: game_box
          path: |
            ./release/out
