name: CI

on:
  push:
    branches: [ main, dev/ci ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main, dev/ci ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc upx-ucl

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | awk '{print "\""$0"\""}' > git_tag.inc
          sed -i 's/git_tag.inc/git_tag.ci.inc/g' game_box.pro
          sed -i 's/$$PWD\/tools\/upx-3.91-amd64_linux\/upx/cp $$DESTDIR\/$$TARGET $$DESTDIR\/game_box_temp; upx-ucl/g' game_box.pro
          qmake -makefile
          make
          cd ./tools/build_deb
          ./build.sh
      
      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: game_box_ubuntu2004
          path: |
            ./release/out

  ubuntu-1804:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc upx-ucl

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | awk '{print "\""$0"\""}' > git_tag.inc
          sed -i 's/git_tag.inc/git_tag.ci.inc/g' game_box.pro
          sed -i 's/$$PWD\/tools\/upx-3.91-amd64_linux\/upx/cp $$DESTDIR\/$$TARGET $$DESTDIR\/game_box_temp; upx-ucl/g' game_box.pro
          qmake -makefile
          make
          cd ./tools/build_deb
          ./build.sh
      
      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: game_box_ubuntu1804
          path: |
            ./release/out
      
  windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0
        with:
          arch: win64_mingw81
          
      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | ./tools/awk/awk.exe '{print \"\\\"\"$0\"\\\"\"}'  > git_tag.inc
          ./tools/sed/sed.exe -i "s/git_tag.inc/git_tag.ci.inc/g" game_box.pro
          qmake -makefile
          mingw32-make
          windeployqt.exe ./release/out/game_box.exe
          Copy-Item C:/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/x86_64-w64-mingw32/lib/*.dll ./release/out/
      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: game_box_windows
          path: |
            ./release/out


  macos:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install Qt
        uses: jurplel/install-qt-action@v2.14.0

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | awk '{print "\""$0"\""}' > git_tag.inc
          qmake -makefile
          make
      
      - name: Upload build asserts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: game_box_macos
          path: |
            ./release/out
