name: linux

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  ubuntu-2004:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.2.0'
          modules: 'qtmultimedia'
          aqtversion: ==2.1.0

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc upx-ucl qt5-default libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libgst-dev

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | awk '{print "\""$0"\""}' > git_tag.inc
          sed -i 's/git_tag.inc/git_tag.ci.inc/g' game_box.pro
          sed -i 's/upx-ucl/cp $$DESTDIR\/$$TARGET $$DESTDIR\/game_box_temp; upx-ucl/g' game_box.pro
          qmake -makefile
          make
          cd ./tools/build_deb
          ./build.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: game_box_ubuntu2004
          path: |
            ./release/out

      - name: Run tests
        run: |
          ./release/out/game_box --version
