name: linux

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  ubuntu-2204:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          modules: 'qtmultimedia'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y make gcc upx-ucl libfuse2

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | awk '{print "\""$0"\""}' > git_tag.inc
          sed -i 's/git_tag.inc/git_tag.ci.inc/g' game_box.pro
          sed -i 's/upx-ucl/cp $$DESTDIR\/$$TARGET $$DESTDIR\/game_box_temp; upx-ucl/g' game_box.pro
          qmake -makefile
          make
          cd ./tools/build_deb
          ./build.sh

      - name: Upload build asserts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: game_box_ubuntu2204
          path: |
            ./release/out

      - name: Run tests
        run: |
          ./release/out/game_box --version
