name: macos

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'games/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.5.3'
          modules: 'qtmultimedia'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source upx

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --dirty --abbrev=10 --tags | awk '{print "\""$0"\""}' > git_tag.inc
          sed -i'.original' -e 's/git_tag.inc/git_tag.ci.inc/g' game_box.pro
          sed -i'.original' -e 's/$$PWD\/tools\/upx-macos\/upx/cp $$DESTDIR\/$$TARGET $$DESTDIR\/game_box_temp; upx/g' game_box.pro
          qmake -makefile
          make
          cd ./release/out
          sudo macdeployqt game_box.app -dmg -verbose=2

      - name: Upload build asserts
        uses: actions/upload-artifact@v4.6.0
        with:
          name: game_box_macos
          path: |
            ./release/out/game_box.dmg

      - name: Run tests
        run: |
          sudo hdiutil attach ./release/out/game_box.dmg
          /Volumes/game_box/game_box.app/Contents/MacOS/game_box --version
